name: release-initramfs

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build initramfs tarball
        # Sadly alpine-make-rootfs needs sudo
        run: sudo bash ./build.sh

      - name: Package build artifacts
        run: sudo zip -r bitpixie-${{ github.ref_name }}.zip *

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bitpixie-${{ github.ref_name }}.zip
