name: release-initramfs

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build initramfs tarball
        # Sadly alpine-make-rootfs needs sudo
        run: sudo bash ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./pxe-server/bitpixie-initramfs
